//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpHomes.Resources.Files {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tooltips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tooltips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpHomes.Resources.Files.Tooltips", typeof(Tooltips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Opens the folder of your project..
        /// </summary>
        internal static string LinksFolder {
            get {
                return ResourceManager.GetString("LinksFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Opens NCC website..
        /// </summary>
        internal static string LinksNCC {
            get {
                return ResourceManager.GetString("LinksNCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Opens Victorian Planning Schemes ResCode website..
        /// </summary>
        internal static string LinksResCode {
            get {
                return ResourceManager.GetString("LinksResCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Create document transmittal from selected revisions and sheets..
        /// </summary>
        internal static string ToolsDocTrans {
            get {
                return ResourceManager.GetString("ToolsDocTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Export selected sheets using company DWG export standards..
        /// </summary>
        internal static string ToolsExpCAD {
            get {
                return ResourceManager.GetString("ToolsExpCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Extracts project data from a PDF and applies it to the Revit Project..
        /// </summary>
        internal static string ToolsProjSetup {
            get {
                return ResourceManager.GetString("ToolsProjSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:
        ///Rotate selected elements counterclockwise to specified angle..
        /// </summary>
        internal static string ToolsRotate {
            get {
                return ResourceManager.GetString("ToolsRotate", resourceCulture);
            }
        }
    }
}
